### ISSUE TITLE
I got matched on a day I don't have matches turned on for

### ISSUE THREAD

**Issue by nicholasbs** [thechutrain/rc-coffee-chats#20]
I received a match this morning, but I have them turned off for Fridays. It's not an issue with my settings, since I confirmed this morning that Coffee Bot has those stored correctly:

![image](https://user-images.githubusercontent.com/50336/56427592-73d72800-628a-11e9-9364-8c50570aa375.png)

**Comment by thechutrain** [comment]
Thanks for letting me know @nicholasbs. This issue should be fixed now with cb306d0e1f152e3948ae74df0b918f1bb0d7082b -- it was silly query error!
