### ISSUE TITLE
Documentation for skipping next match is wrong

### ISSUE THREAD

**Issue by nicholasbs** [thechutrain/rc-coffee-chats#28]
It looks like the documentation for how to skip your next match is wrong:

![image](https://user-images.githubusercontent.com/50336/56589042-7f8c5c80-65b2-11e9-8c10-4fbabd3f6ca2.png)

I assume this should be `UPDATE SKIP 1`, since running `UPDATE SKIP 0` results in the bot saying "Your skip next match is now set to: FALSE"

**Comment by thechutrain** [comment]
That's correct, thanks for pointing that out @nicholasbs. I'll fix it before tonight's cron job
