### ISSUE TITLE
turning off warnings broken?

### ISSUE THREAD

**Issue by nickav** [thechutrain/rc-coffee-chats#35]
turning off warnings doesn't seem to actually do anything. see attached screenshot

<img width="782" alt="Screen Shot 2019-04-23 at 7 46 59 PM" src="https://user-images.githubusercontent.com/5448363/56672867-29d4b480-6685-11e9-9327-df7a0b65b3dc.png">

**Comment by thechutrain** [comment]
Confirmed that this is a bug. The confusion stems from how this setting is stored in the table (column name is `warning_exception`) versus how end users (including myself) were perceiving the their *warnings* setting.

## Current Incorrect Implementation
Warnings On --> warning_exception = "1"
Warnings Off --> warning_exception = "0"

## Possible suggested solution
Change the column name to warning_notifications?
OR simply fix the warning notification sql

**Comment by thechutrain** [comment]
fixed in version 2.0.2
