### ISSUE TITLE
Virtual coffee chat

### ISSUE THREAD

**Issue by gs0510** [thechutrain/rc-coffee-chats#5]
Allow an option to virtually match with another Recursers for a coffee chat using the same opt-in system? Maybe match people in similar time-zones?

**Comment by thechutrain** [comment]
Hi @gs0510 that's a great idea and something we are considering when adding in more alumni-oriented features. 

I think there are additional steps we'd have to take before getting there -- such as being able to adjust the weekly frequency of your desired matching (biweekly, or once a month kind of thing) as well as storing the location/timezone that other Recursers are in. But *virtual matches* would be a great opt-in feature. 

Open to suggestions and happy to chat more in person as well!

**Comment by bdelanghe** [comment]
@thechutrain with RC moving to be virtual-only and the addition of the zoom link it seems like this has been fully implemented. Maybe this issue can be closed?

**Comment by gs0510** [comment]
@bdelanghe Thanks for pointing this out! This can be closed ^_^
