### ISSUE TITLE
Coffeebot should open a conversation with the two people being matched.

### ISSUE THREAD

**Issue by malisper** [thechutrain/rc-coffee-chats#6]
The current workflow is:

1. Coffeebot messages you that you've been matched with X.
2. You open a conversation with X.
3. You ask X if they are up to meet at a given time.

A slightly better workflow is:

1. Coffeebot opens a conversation with you and X.
2. You respond in the conversation if you are up to meet at a given time.

**Comment by thechutrain** [comment]
Briefly looking at the Zulip API, it seems like this can be done easily; the example implies that you can send a private message to more than one user. 
DOCS: https://zulipchat.com/api/send-message

Perhaps this would also be useful to use when a matched pair cannot actually meet and either one of users can notify chat bot that the chat did not occur.

**Comment by thechutrain** [comment]
One way to implement this is to create a new function in `msg-sender.ts` that is a simple wrapper of the `sendGenericMessage()` function. This would also help clean up the message sending portion in the `crons/matchify/index.ts`

**Comment by thechutrain** [comment]
Zulip's API does support this and it I got it working for sending log messages as a group message to all maintainers.  The message sender wrapper function, `sendGenericMessage()` does support this.

See https://github.com/thechutrain/rc-coffee-chats/blob/master/src/zulip-messenger/msg-sender.ts#L16
